[2022-11-16 01:30:10,646] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-17T00:00:00+00:00 [queued]>
[2022-11-16 01:30:15,262] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-17T00:00:00+00:00 [queued]>
[2022-11-16 01:30:15,344] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:30:15,378] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-16 01:30:15,403] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:30:21,870] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): hello_task> on 2022-02-17T00:00:00+00:00
[2022-11-16 01:30:23,669] {standard_task_runner.py:52} INFO - Started process 283 to run task
[2022-11-16 01:30:25,659] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_task', '2022-02-17T00:00:00+00:00', '--job-id', '48', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/index.py', '--cfg-path', '/tmp/tmpi2patf3m', '--error-file', '/tmp/tmp61sa64lu']
[2022-11-16 01:30:25,777] {standard_task_runner.py:77} INFO - Job 48: Subtask hello_task
[2022-11-16 01:30:32,780] {logging_mixin.py:104} INFO - Running <TaskInstance: hello_world.hello_task 2022-02-17T00:00:00+00:00 [running]> on host 001906ffd7c9
[2022-11-16 01:30:38,837] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-17T00:00:00+00:00
[2022-11-16 01:30:38,898] {logging_mixin.py:104} INFO - hi everyone
[2022-11-16 01:30:38,914] {python.py:118} INFO - Done. Returned value was: hello world
[2022-11-16 01:30:39,937] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20220217T000000, start_date=20221116T013011, end_date=20221116T013039
[2022-11-16 01:30:44,474] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-16 01:30:46,354] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-16 01:30:46,924] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 283
[2022-11-16 01:30:47,063] {process_utils.py:66} INFO - Process psutil.Process(pid=283, status='terminated', exitcode=0, started='01:30:22') (283) terminated with exit code 0
