[2022-11-16 01:28:57,456] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-07T00:00:00+00:00 [queued]>
[2022-11-16 01:28:58,884] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-07T00:00:00+00:00 [queued]>
[2022-11-16 01:28:58,938] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:28:58,957] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-16 01:28:58,996] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:29:00,315] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): hello_task> on 2022-02-07T00:00:00+00:00
[2022-11-16 01:29:00,438] {standard_task_runner.py:52} INFO - Started process 239 to run task
[2022-11-16 01:29:00,676] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_task', '2022-02-07T00:00:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/index.py', '--cfg-path', '/tmp/tmp7gb7vd9q', '--error-file', '/tmp/tmpryylu1wt']
[2022-11-16 01:29:00,718] {standard_task_runner.py:77} INFO - Job 38: Subtask hello_task
[2022-11-16 01:29:02,916] {logging_mixin.py:104} INFO - Running <TaskInstance: hello_world.hello_task 2022-02-07T00:00:00+00:00 [running]> on host 001906ffd7c9
[2022-11-16 01:29:05,000] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-07T00:00:00+00:00
[2022-11-16 01:29:05,062] {logging_mixin.py:104} INFO - hi everyone
[2022-11-16 01:29:05,086] {python.py:118} INFO - Done. Returned value was: hello world
[2022-11-16 01:29:07,899] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20220207T000000, start_date=20221116T012857, end_date=20221116T012907
[2022-11-16 01:29:11,138] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-16 01:29:11,448] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 239
[2022-11-16 01:29:11,477] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-11-16 01:29:12,115] {process_utils.py:66} INFO - Process psutil.Process(pid=239, status='terminated', exitcode=1, started='01:28:59') (239) terminated with exit code 1
