[2022-11-16 01:30:50,961] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-21T00:00:00+00:00 [queued]>
[2022-11-16 01:30:52,972] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-21T00:00:00+00:00 [queued]>
[2022-11-16 01:30:53,022] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:30:53,029] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-16 01:30:53,060] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:30:53,665] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): hello_task> on 2022-02-21T00:00:00+00:00
[2022-11-16 01:30:53,803] {standard_task_runner.py:52} INFO - Started process 293 to run task
[2022-11-16 01:30:54,026] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_task', '2022-02-21T00:00:00+00:00', '--job-id', '52', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/index.py', '--cfg-path', '/tmp/tmp0hmkj7i4', '--error-file', '/tmp/tmpht8zt5za']
[2022-11-16 01:30:54,043] {standard_task_runner.py:77} INFO - Job 52: Subtask hello_task
[2022-11-16 01:30:55,033] {logging_mixin.py:104} INFO - Running <TaskInstance: hello_world.hello_task 2022-02-21T00:00:00+00:00 [running]> on host 001906ffd7c9
[2022-11-16 01:30:56,421] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-21T00:00:00+00:00
[2022-11-16 01:30:56,474] {logging_mixin.py:104} INFO - hi everyone
[2022-11-16 01:30:56,497] {python.py:118} INFO - Done. Returned value was: hello world
[2022-11-16 01:30:57,803] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20220221T000000, start_date=20221116T013051, end_date=20221116T013057
[2022-11-16 01:31:00,279] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-16 01:31:01,012] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-16 01:31:01,398] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 293
[2022-11-16 01:31:01,437] {process_utils.py:66} INFO - Process psutil.Process(pid=293, status='terminated', exitcode=0, started='01:30:53') (293) terminated with exit code 0
