[2022-11-16 01:29:35,797] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-12T00:00:00+00:00 [queued]>
[2022-11-16 01:29:37,279] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-12T00:00:00+00:00 [queued]>
[2022-11-16 01:29:37,301] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:29:37,362] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-16 01:29:37,377] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:29:38,840] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): hello_task> on 2022-02-12T00:00:00+00:00
[2022-11-16 01:29:39,006] {standard_task_runner.py:52} INFO - Started process 265 to run task
[2022-11-16 01:29:39,304] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_task', '2022-02-12T00:00:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/index.py', '--cfg-path', '/tmp/tmpknf0kvn7', '--error-file', '/tmp/tmpnp9yuvjn']
[2022-11-16 01:29:39,363] {standard_task_runner.py:77} INFO - Job 44: Subtask hello_task
[2022-11-16 01:29:43,823] {logging_mixin.py:104} INFO - Running <TaskInstance: hello_world.hello_task 2022-02-12T00:00:00+00:00 [running]> on host 001906ffd7c9
[2022-11-16 01:29:49,866] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-12T00:00:00+00:00
[2022-11-16 01:29:50,005] {logging_mixin.py:104} INFO - hi everyone
[2022-11-16 01:29:50,047] {python.py:118} INFO - Done. Returned value was: hello world
[2022-11-16 01:29:51,514] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20220212T000000, start_date=20221116T012936, end_date=20221116T012951
[2022-11-16 01:29:58,048] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-16 01:29:58,709] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 265
[2022-11-16 01:29:59,229] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-11-16 01:30:01,024] {process_utils.py:66} INFO - Process psutil.Process(pid=265, status='terminated', exitcode=1, started='01:29:38') (265) terminated with exit code 1
